dataset:
  name: Scannet
  # path/to/your/dataset
  dataset_path:
  cache_dir:
  steps_per_epoch_train: 500

model:
  name: PointPillars
  # path/to/your/checkpoint
  ckpt_path:

  point_cloud_range: [-6, 0, 0, 6, 10, 4]   # TBC
  classes: [
      'cabinet', 'bed', 'chair', 'sofa', 'table', 'door', 'window',
      'bookshelf', 'picture', 'counter', 'desk', 'curtain',
      'refrigerator', 'showercurtrain', 'toilet', 'sink', 'bathtub',
      'garbagebin'
  ]

  loss:
    focal:
      gamma: 2.0
      alpha: 0.25
      loss_weight: 1.0
    smooth_l1:
      beta: 0.11
      loss_weight: 2.0
    cross_entropy:
      loss_weight: 0.2

  voxelize:
    max_num_points: 32
    voxel_size: &vsize
      [0.025, 0.025, 4]             # TBC
    max_voxels: [16000, 40000]      # [P_train, P_test]

  voxel_encoder:
    in_channels: 3
    feat_channels: [64]
    voxel_size: *vsize

  scatter:
    in_channels: 64
    output_shape: [496, 432]

  backbone:
    in_channels: 64
    out_channels: [64, 128, 256]
    layer_nums: [3, 5, 5]
    layer_strides: [2, 2, 2]

  neck:
    in_channels: [64, 128, 256]
    out_channels: [128, 128, 128]
    upsample_strides: [1, 2, 4]
    use_conv_for_no_stride: false

  head:
    in_channels: 384
    feat_channels: 384
    nms_pre: 100
    score_thr: 0.1
    ranges: [                   # TBC
      [-6, 0, 0, 6, 10, 2],
      [-6, 0, 0, 6, 10, 2],
      [-6, 0, 0, 6, 10, 2],
      [-6, 0, 0, 6, 10, 2],
      [-6, 0, 0, 6, 10, 2],
      [-6, 0, 0, 6, 10, 2],
      [-6, 0, 0, 6, 10, 2],
      [-6, 0, 0, 6, 10, 2],
      [-6, 0, 0, 6, 10, 2],
      [-6, 0, 0, 6, 10, 2],
      [-6, 0, 0, 6, 10, 2],
      [-6, 0, 0, 6, 10, 2],
      [-6, 0, 0, 6, 10, 2],
      [-6, 0, 0, 6, 10, 2],
      [-6, 0, 0, 6, 10, 2],
      [-6, 0, 0, 6, 10, 2],
      [-6, 0, 0, 6, 10, 2],
      [-6, 0, 0, 6, 10, 2]
    ]
    sizes:
        [[1.75, 1.75, 0.96],
        [2.37, 2.37, 1.19],
        [0.79, 0.79, 0.71],
        [2.35, 2.35, 0.84],
        [2.05, 2.05, 0.63],
        [1.05, 1.05, 1.72],
        [2.02, 2.02, 1.17],
        [2.66, 2.66, 1.69],
        [0.93, 0.93, 0.57],
        [3.11, 3.11, 0.29],
        [2.38, 2.38, 0.87],
        [2.48, 2.48, 1.65],
        [0.93, 0.93, 1.31],
        [0.68, 0.68, 1.7],
        [0.72, 0.72, 0.72],
        [0.67, 0.67, 0.31],
        [1.52, 1.52, 0.52],
        [1.19, 1.19, 0.65]]

    rotations: [0, 1.57]
    iou_thr: [
        [0.35, 0.5],
        [0.35, 0.5],
        [0.35, 0.5],
        [0.35, 0.5],
        [0.35, 0.5],
        [0.35, 0.5],
        [0.35, 0.5],
        [0.35, 0.5],
        [0.35, 0.5],
        [0.35, 0.5],
        [0.35, 0.5],
        [0.35, 0.5],
        [0.35, 0.5],
        [0.35, 0.5],
        [0.35, 0.5],
        [0.35, 0.5],
        [0.35, 0.5],
        [0.35, 0.5],
    ]                # TBC

  augment:
    PointShuffle: True
    ObjectRangeFilter:
      point_cloud_range: [-6, 0, 0, 6, 10, 4]

pipeline:
  name: ObjectDetection
  test_compute_metric: true
  batch_size: 32
  val_batch_size: 32
  save_ckpt_freq: 5
  max_epoch: 200
  main_log_dir: logs
  train_sum_dir: logs/train_log
  grad_clip_norm: 2

  optimizer:
    lr: 0.001
    betas: [0.95, 0.99]
    weight_decay: 0.01

  # evaluation properties
  overlaps: [
      0.5, 0.5, 0.5,
      0.5, 0.5, 0.5,
      0.5, 0.5, 0.5,
      0.5, 0.5, 0.5,
      0.5, 0.5, 0.5,
      0.5, 0.5, 0.5
  ]                     # TBC
  similar_classes: {
  }
  difficulties: [0, 1, 2, 3, 4]
